version: "3.8"
services:
    nginx:
      build:
        context: ./
        dockerfile: Docker/nginx/Dockerfile
      volumes:
        - ./:/var/www
      ports:
        - "8080:80"
      depends_on:
        - php-fpm
      container_name: nginx-dev
    php-fpm:
      build:
        context: ./
        dockerfile: Docker/fpm/Dockerfile
      volumes:
        - ./:/var/www
        - ./Docker/fpm/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        - ./Docker/fpm/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
      depends_on:
        - redis
        - mySQL80-dev
      container_name: php-fpm-dev
    php-cli:
      build:
        context: ./
        dockerfile: Docker/cli/Dockerfile
      volumes:
        - ./:/var/www
      tty: true
      container_name: php-cli-dev
    mySQL80-dev:
      image: mysql:8.0
      ports:
        - "3307:3306"
      environment:
        - MYSQL_DATABASE=${DB_DATABASE}
        - MYSQL_USER=${DB_USERNAME}
        - MYSQL_PASSWORD=${DB_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      volumes:
        - ../DB_space/${DB_STORAGE_PATH}:/var/lib/mysql
      container_name: mySQL80-dev
    redis:
      image: redis:7.2.4
      ports:
        - "6380:6379"
      container_name: redis-dev
